### ISSUE TITLE
Could not resolve type with token 01000002 (from typeref, class/assembly ObjCRuntime.BindingImplAttribute, Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065)

### ISSUE THREAD

**Issue by CarLoOSX** [martijn00/LottieXamarin#161]
I'm having this problem after updating xcode version 9.2 to 9.3 and getting the las version of stable chanel in visual studio for mac.

Any suggestion?

**Comment by CarLoOSX** [comment]
Package version : 2.5.2.1

**Comment by CarLoOSX** [comment]
I'm not having this problem in the last version of xamarin.android, visual studio etc.

**Comment by CarLoOSX** [comment]
Need help please 🙀

**Comment by KennethKr** [comment]
I'm facing the same issue. But this is my first time using lottie for iOS, so I'm not sure.

**Comment by KennethKr** [comment]
Downgrade to 2.5.1 works.

**Comment by CarLoOSX** [comment]
Hey @KennethKr I'll try this after afternoon and I'll send you a feedback ! Thanks so much 😸

**Comment by CarLoOSX** [comment]
Working on 2.5.1 @KennethKr !!!💃

**Comment by hinojosachapel** [comment]
After upgrading everything today, I got the same error (VS for Mac). Downgrading to version 2.5.1 solved the issue.

**Comment by Frank37** [comment]
After upgrading everything today, I got the same error (VS for Mac). Downgrading **Lottie** from Version 2.5.2.1 to version 2.5.1 solved the issue.
Thanx **@KennethKr**

**Comment by ArtjomP** [comment]
I have the same issue

**Comment by syedhoque89** [comment]
I have same experience. Whats going on? Regression?

**Comment by martijn00** [comment]
As also mentioned in: https://github.com/martijn00/LottieXamarin/issues/159, https://github.com/martijn00/LottieXamarin/issues/157, https://github.com/martijn00/LottieXamarin/issues/147, and https://github.com/martijn00/LottieXamarin/issues/140
You have to be on the latest Xamarin stable to be able to run it. Otherwise there is a mismatch between the Xamarin version you compile against and which was used to build Lottie.

Version 7.5 (build 1254)
Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
Mac 4.4.0.36 (master / 0c7c49a6)
Android Version: 8.3.0.19 (Visual Studio Community)
IOS Version: 11.10.1.177 (Visual Studio Community)
Windows Visual Studio 15.7.1
