### ISSUE TITLE
Animation looks different on iOS

### ISSUE THREAD

**Issue by galadril** [martijn00/LottieXamarin#195]
### Steps to reproduce :scroll:
1. Use my ship json file
2. Run on Android
3. Run on iOS

### Expected behavior :thinking:
I use the lottie library for Xamarin Forms, and the same animation file should renderer the same on iOS and Android.

### Actual behavior :bug:
This ship animation looks different on Android / iOS

**Android:**
![afbeelding](https://user-images.githubusercontent.com/14561640/47841856-3e617f80-ddbb-11e8-9104-63cde99223f6.png)

**iOS:**
![afbeelding](https://user-images.githubusercontent.com/14561640/47841867-428d9d00-ddbb-11e8-86b2-fd454f8b07c5.png)

Please PM me for a lottie json file (can't share it on github)

### Configuration :wrench:

**Version:** 2.6.3

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by fabionuno** [comment]
@galadril  Lottie for Xamarin is just a binding of the native Lottie libraries and those libraries has completely different render engines between them.

So you can find different issues between versions.
Since your issue is related to the render engine you need to address this to the [Lottie iOS](https://github.com/airbnb/lottie-ios/issues) team.

Unfortunately there isn't we can do about it.

**Comment by galadril** [comment]
Unfortunately,.. thanks for the response!

**Comment by galadril** [comment]
Are you using the latest iOS/Android lottie packages? Or are you planning on upgrading?>?

**Comment by adrianknight89** [comment]
#233 might as well be the same issue. Seems like the iOS rendering engine isn't very stable.

**Comment by OdetteP** [comment]
See answer #233
