### ISSUE TITLE
Loading animation json from memory

### ISSUE THREAD

**Issue by zwanderer** [martijn00/LottieXamarin#220]
We have a need to customize some animations in our application, for that to work we either need to generate the json dynamically or load it from an external resource.

Is there any example on how to load the animation from a stream or string? I've only found how to load it from a resource file.

**Comment by EdwardRushDeveloper** [comment]
What I have found, currently this Xamarin Forms implementation for Android does not support loading from other than an Asset or Resource. It does work in iOS when I move a JSON file to a folder and then load it. But when trying the same thing with Android, it does not work. I have the same question about it because we want to dynamically download to our devices a JSON file with a different animation based on a special circumstance. I think the underlying Lottie Java code does support it, but the renderer in this current implementation does not. I am hoping that the authors can help us on this, and I imagine they are like everyone else......They have a lot of other things that they have to do other than this project. But it would be a great addition.

**Comment by OdetteP** [comment]
Did you solve this issue?

**Comment by iWeaverMan** [comment]
Сhange required for Android. 
With the full file path, load not from the resources.
