### ISSUE TITLE
Old version for Android and iOS?

### ISSUE THREAD

**Issue by mathiasnielsen** [martijn00/LottieXamarin#221]
## 🚀 Feature Requests

Are there any plans on updating this binding, to use the Lottie 3.0+ stuff? And if yes, when? :)

**Comment by martijn00** [comment]
For Android we need to wait for Xamarin to release AndroidX support. On iOS I would like to see if @fabionuno can update the bindings?

**Comment by fabionuno** [comment]
@martijn00  I think I will be able to work on this update this weekend

**Comment by mathiasnielsen** [comment]
Okay, that sounds great :D

**Comment by martijn00** [comment]
@fabionuno how is it going? Did you have a chance to look at it?

**Comment by mathiasnielsen** [comment]
Any update on the update?

**Comment by fabionuno** [comment]
Sorry for the delayed feedback, unfortunately I have had little free time in the last months. 

I'm working on the binds but they aren't stable yet. There are some random runtime errors in simulator and device. Tonight I'll work on this issue a little more.

**Comment by fabionuno** [comment]
Due to Xamarin's lack of official support to bind Swift libraries, I can not seem to get a 100% Xamarin version compatible with the Swift library.

I have tried some hacks to bind Swift libraries, but things like Decodable and Swift extensions are more complex to resolve.

Lottie folks even created an[ Objective-C compatible class ](https://github.com/airbnb/lottie-ios/tree/master/lottie-swift/src/Public/iOS/Compatibility) to give them access to some Lottie features in Objective-C projects.
But it is basic and doesn't support loading animations from a path or URL.

I've added a few more methods in the compatibility class and at this moment I have an alpha version able to load an Animation from the Bundle and control it.

To have a more professional support I will have to implement some more Objective-C proxy classes.

At this moment we don't have support to:
- Dynamic Animation Properties
- Adding Views to Animations
- Image Provider
- BundleImageProvider
- FilepathImageProvider
- Animation Cache
- LRUAnimationCache
- Value Providers
- Primitives
- Prebuilt Providers
- Animated Control
- Animated Switch
- Animated Button

If read an animation from Bundle and control it,  are enough in most cases. I believe we can release a version 3.0.6 Alpha on NuGet.
What do you think @martijn00 ?

**Comment by martijn00** [comment]
@fabionuno I've put out new versions for the current code base. Can you make a PR for the alpha?
