### ISSUE TITLE
Xamarin Forms Shell - Lottie 3.1.0 NuGet doesn't show animation on Android

### ISSUE THREAD

**Issue by rfernandez** [martijn00/LottieXamarin#259]
## 🐛 Bug Report

I have a Xamarin Forms Shell Application for Android and iOS. I use a Lottie Animation. 
The 3.1.0 version doesn't show animation. 
The 3.0.4 version works well.

### Expected behavior

I would like use the same version of NuGet Lottie: 3.1.0 for two platforms.

### Reproduction steps

1. Create a new Xamarin Forms Shell project.

2. Add the Lottie NuGet package to the project and select the three options (including iOS and Android)

3. Create a XAML view with this contenct:

```xml
                ...
                <forms:AnimationView
                x:Name="LottieView" 
                Animation="btnqr.json"
                Loop="False"
                AutoPlay="False"
                OnFinish="Handle_OnFinish"
                HeightRequest="70"
                WidthRequest="70"
                VerticalOptions="End"
                HorizontalOptions="End"
                Margin="0,0,30,30" />
        </Grid>
```

4. In the code behind I start the animation:

```c#
protected override async void OnAppearing()
        {
            // Esperamos un tiempo hasta que se visualice la página correspondiente.
            // Una vez que se ve la página, iniciamos la animación
            await StartAnimationWithDelay();
        }

        private async Task StartAnimationWithDelay()
        {
            await Task.Run(() =>
            {
                Device.StartTimer(TimeSpan.FromSeconds(1), () =>
                {
                    lottieView = NameScopeExtensions.FindByName<AnimationView>(this, "LottieView");
                    lottieView.Play();

                    return false;
                });
            });
        }

        // Capturamos el evento de finalización de la animación y la volvemos a lanzar
        // las veces acordadas
        private void Handle_OnFinish(object sender, EventArgs e)
        {
            if(++counter < 2)
            {
                lottieView.Play();
            }
        }
```

5. With the Android simulator and the physical device I can not display the animation with the latest 3.1.0 Lottie version.

### Configuration

**IDE:** Visual Studio 2019 for Mac

**Project configuration:**
- Com.Airbnb.Xamarin.Forms.Lottie: 3.1.0
- Xamarin.Essentials: 1.5.0
- Xamarin.Forms: 4.5.0.356

**Lottie Version:** 3.1.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by RicolabRico** [comment]
Same problem with:
`   <forms:AnimationView 
     Grid.RowSpan="3"
  	x:Name="animationView" 
	Animation="test.json" 
    Loop="true" 
	AutoPlay="true"
	VerticalOptions="FillAndExpand" 
	HorizontalOptions="FillAndExpand" />`
on android with version 3.1.  It was ok with 3.0.4

**Comment by jherink** [comment]
I had the same problem upgrading from 3.0.3 to 3.1.0

I use several AnimationViews with various animations throughout the app and none of them worked.  All worked on iOS.  Nothing special about my animations, here is one use:

<forms:AnimationView x:Name="AnimationView" 
                                       Animation="app-loader.json" 
                                       AutoPlay="True" 
                                       Loop="true"
                                       WidthRequest="80"
                                       HeightRequest="80"
                                       VerticalOptions="FillAndExpand"
                                       HorizontalOptions="FillAndExpand" />
 
It may have been intentional in the release of 3.1.0 but I couldn't find anything saying this change was on purpose.  I did need to remove my AnimationViewRenderer.Init() from MainActivity.cs to get it to compile because the namespace "Lottie.Forms.Droid" couldn't be found.

**Comment by rfernandez** [comment]
I have used the 3.0.4 and 3.1.0 and it is not necessary the "init" process. The classes (package) have disappeared too. This way is documented, I think to remember.

**Comment by jBijsterboschNL** [comment]
I also had the same issue since upgrading the Com.Airbnb.Xamarin.Forms.Lottie NuGet package from v3.0.0 to v3.1.0.

In a different project, by accident, I found out that when updating the Com.Airbnb.Android.Lottie NuGet package to the latest version (v3.4.0) you'll need to target Android SDK 10 (or above). This warning is not given when updating the Com.Airbnb.Xamarin.Forms.Lottie NuGet package. BUT if you change your Android SDK target to Android 10 on your own Android project, the Lottie animation works again and you are able to use the Com.Airbnb.Xamarin.Forms.Lottie v3.1.0 NuGet package. :)

@Martijn00: maybe in a new NuGet package release this warning can also be added to the Com.Airbnb.Xamarin.Forms.Lottie NuGet package to prevent issues (read: frustration) like this?! :)
