### ISSUE TITLE
Repeater and shape merge/subtract are not working

### ISSUE THREAD

**Issue by PaulHoets** [martijn00/LottieXamarin#49]
Hi there.

I found that a particular test I created didn't work fully, although it still displayed and animated, which was something. The trashcan lid handle had a subtract, but it didn't work, and the central bars on the trashcan had a x3 repeater, but only the original bar on the left displayed.

Repeater is a luxury (though it would be nice), but if the subtract could be used, that would be a very important step forward. Or does it already work, and I am doing something wrong?

Included is the original AE file, as well as the exported .json file.

Is there any way to verify that an exported .json will not conflict with the current state of the art with Lottie? Its very hit and miss, and its hard to learn, because there is no indicator about why a certain animation completely fails to display.

Thank you for the hard work, and best regards.

[trashcan.zip](https://github.com/martijn00/LottieXamarin/files/878729/trashcan.zip)

![trashcan - simulator](https://cloud.githubusercontent.com/assets/8898932/24451080/5cc06d42-14b8-11e7-9292-a2c982b3c753.png)
![trashcan - ae](https://cloud.githubusercontent.com/assets/8898932/24451081/5cc6f428-14b8-11e7-83a6-d9d1ab7cdd21.png)

**Comment by fabionuno** [comment]
@PaulHoets I think it's not a specific problem with Lottie. 
I have played your JSON with [Bodymovin](https://github.com/bodymovin/bodymovin) HTML player and got the same problem as you. 
Maybe you are using some feature not supported in Bodymovin.
Can you refer this issue to the Bodymovin team since the problem happens in html player too?

![trashcan](https://cloud.githubusercontent.com/assets/5355384/24509284/5bdb0796-153c-11e7-8854-dc2973182d52.png)

**Comment by PaulHoets** [comment]
Perhaps. I'll look more in that direction. Thank you very much!
