### ISSUE TITLE
UWP Xamarin Forms Example Please

### ISSUE THREAD

**Issue by JimSEOW** [martijn00/LottieXamarin#66]
Now that LottieUWP works. 
Please add an UWP XF example here. Thank you
https://github.com/martijn00/LottieXamarin/tree/develop/Examples

**Comment by azchohfi** [comment]
Working on it!

**Comment by SKLn-Rad** [comment]
I'm probably just being too hasty! But the sample you gave appears to be ridiculously slow?
![image](https://user-images.githubusercontent.com/2837970/27337570-bd148946-55ca-11e7-886c-20fa60ff1379.png). Will give it a go later with my own animations :) Keep up the great work!

**Comment by azchohfi** [comment]
Yes... It is still not even close from perfection. That's why it is alpha 🐱‍👓
There is work being done to really improve this (XAMLDIsplay branch, https://github.com/azchohfi/LottieUWP/tree/XAMLDisplay) Should be the "next big thing", removing the WriteableBitmapExt dependency and using UWP Path classes) for drawing, but it's not done yet.

**Comment by JimSEOW** [comment]
@azchohfi  Great, Looking forwards to more optimized version. Perhaps in my case, it is so slow that nothing appear except the slider :-)

**Comment by OlegKlym** [comment]
What should be the buidl action in the UWP json file?

**Comment by azchohfi** [comment]
It should be good enough now for public use. Try updating to latest version.
I think this issue should be closed. There is already a sample app.
@martijn00
