### ISSUE TITLE
Trouble with simple text?

### ISSUE THREAD

**Issue by rmawani** [martijn00/LottieXamarin#76]
First off, just wanted to say what a great job you have done on this wonderful plugin!

I am working on a proof-of-concept for a client and decided to incorporate some AE Animation effects into the project.

For some odd reason, I'm seeing a weird issue with my text whereby any letters that should be rendered with transparency are in fact filled (such as "o" for example).

I'm attaching a sample JSON file along with the image of the issue happening on the iOS Simulator (have not tested on Android as yet)

[Sample JSON](https://www.dropbox.com/s/epm9cd0gfyqs2uw/TestComp.json?dl=0)
[Simulator Screenshot](https://www.dropbox.com/s/37elle9gt5nsrey/TestCompScreen.png?dl=0)

As far as I can surmise, it looks like an issue with the Merge Path that AE creates in order to produce the cutout area of letters/numbers with holes in them. How can I rectify this?

Any help would be greatly appreciated!

R

Edit: Just tried the previewing the JSON file in LottiePreview @ [LottieFiles](https://www.lottiefiles.com/preview) and it seems to display correctly without issue.

**Comment by fabionuno** [comment]
Thank you @rmawani.

The [LottieFiles](https://www.lottiefiles.com/preview) uses the [bodymovin](https://github.com/bodymovin/bodymovin) render engine that is completely different from the Lottie iOS render engine just as Lottie Android render engine.

So you can find different issues among versions.
I have tested your JSON using Lottie Android 2.1.0 and it looks great.

Since your issue is related to the render engine you need to address this to the [Lottie iOS](https://github.com/airbnb/lottie-ios/issues) team.
At this moment they are working on a complete new render engine.

**Comment by rmawani** [comment]
Thanks for the feedback!

I just finished trying out my JSON file on Android and it does seem fine.

So, I guess I'll just wait until there is an update to Lottie iOS and then
take it up with them from there. Seems like they will fix the issues I'm
having with my animations in the next release...

Thanks again!

__
Best Regards,

Riz Mawani
